# Generated by Django 3.2 on 2022-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(default='guest', max_length=200),
        ),
    ]
