# Generated by Django 3.2 on 2022-02-05 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
